workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Dodaj prywatne repo CocoaPods (jeśli istnieje)
        script: |
          pod repo add gonativeio-gonative-specs https://github.com/gonativeio/gonative-specs.git || echo "Repo już istnieje"
      - name: Instaluj zależności
        script: |
          pod install
      - name: Build IPA
        script: |
          xcodebuild -workspace Journal.xcodeproj  -scheme Journal -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $HOME/build/MyApp.xcarchive
