workflows:
  ios-build:
    name: Build iOS IPA
    environment:
      xcode: latest
    scripts:
      - name: Dodaj repo GoNative
        script: |
          pod repo add gonativeio-gonative-specs https://github.com/gonativeio/gonative-specs.git || true

      - name: Instaluj zależności
        script: |
          rm Podfile.lock || true
          pod install --repo-update

      - name: Build IPA
        script: |
          xcodebuild -workspace DailyJournal.xcworkspace \
                     -scheme DailyJournal \
                     -sdk iphoneos \
                     -configuration Release \
                     archive -archivePath $CM_BUILD_DIR/MyApp.xcarchive
    artifacts:
      - $CM_BUILD_DIR/**/MyApp.xcarchive
