workflows:
  ios-build:
    name: Build iOS IPA
    environment:
      xcode: latest
    scripts:
      - name: Instaluj zależności
        script: |
          pod install
      - name: Build IPA bez podpisu
        script: |
          xcodebuild -workspace DailyJournal.xcworkspace \
                     -scheme DailyJournal \
                     -sdk iphoneos \
                     -configuration Debug \
                     -allowProvisioningUpdates \
                     CODE_SIGNING_ALLOWED=NO \
                     archive -archivePath $CM_BUILD_DIR/MyApp.xcarchive
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/MyApp.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath $CM_BUILD_DIR/ipa \
                     CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ipa/*.ipa
