workflows:
  ios-build:
    name: Build iOS IPA
    environment:
      xcode: latest
    scripts:
      - name: Instaluj zależności
        script: |
          pod install
      - name: Build IPA
        script: |
          xcodebuild -workspace DailyJournal.xcworkspace \
                     -scheme DailyJournal \
                     -sdk iphoneos \
                     -configuration AppStoreDistribution \
                     archive -archivePath $CM_BUILD_DIR/MyApp.xcarchive
    artifacts:
      - build/ios/ipa/*.ipa
