workflows:
  ios-build:
    name: Build iOS IPA
    environment:
      xcode: latest
    scripts:
      - name: Instaluj zależności
        script: |
          pod install
      - name: Build IPA
        script: |
          xcodebuild -workspace DailyJournal.xcworkspace \
                     -scheme DailyJournal \
                     -sdk iphoneos \
                     -configuration Debug \
                     -archivePath $CM_BUILD_DIR/MyApp.xcarchive \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_IDENTITY="" \
                     DEVELOPMENT_TEAM=""
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/MyApp.xcarchive \
                     -exportPath $CM_BUILD_DIR/ipa \
                     -exportOptionsPlist ExportOptions.plist
    artifacts:
      - ipa/*.ipa
