workflows:
  ios-build:
    name: Build iOS IPA
    environment:
      xcode: latest
    scripts:
      - name: Instaluj zależności
        script: |
          pod install
      - name: Build IPA
        script: |
          xcodebuild -workspace DailyJournal.xcworkspace \
                     -scheme DailyJournal \
                     -sdk iphoneos \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     CODE_SIGNING_ALLOWED=NO \
                     archive -archivePath $CM_BUILD_DIR/MyApp.xcarchive
    artifacts:
      - $CM_BUILD_DIR/**/*.ipa
