workflows:
  ios-build:
    name: Build iOS IPA (No Signing)
    environment:
      xcode: latest
    scripts:
      - name: Dodaj repo gonativeio (jeśli nie istnieje)
        script: |
          pod repo add gonativeio-gonative-specs https://github.com/gonativeio/gonative-specs.git || true

      - name: Instaluj zależności
        script: |
          rm -f Podfile.lock
          pod install --repo-update

      - name: Build IPA bez podpisu
        script: |
          set -e
          xcodebuild clean -workspace DailyJournal.xcworkspace \
                           -scheme DailyJournal \
                           -sdk iphoneos \
                           -configuration Release

          xcodebuild archive \
            -workspace DailyJournal.xcworkspace \
            -scheme DailyJournal \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/MyApp.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER=""

          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/MyApp.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist exportOptions.plist \
            -allowProvisioningUpdates
    artifacts:
      - ipa/*.ipa
