name: Renovate

on:
  schedule:
    - cron: '0 2 * * 0'  # Runs weekly on Sundays at 2 AM UTC
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          repositories: "gonative-ios-private"

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.17
        with:
          token: ${{ steps.app-token.outputs.token }}
          configurationFile: renovate.json
